language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: noTR/tRVhGTn5XeyDz4xIsbBwGtcThRobWWTkbdnC8Pb0O4+4W7FpYghW169ZrzbCn5DPRXgR6uYeS/A4z+0i+YwyAQpPxwtv9NLtis871jPA4uK2LIgkCmtSwyG5BFlicgXmAlTOOj2QhnOlEe/eUuIgvcabWZ/UU7WDR/cMB/OLm6tD/BEvWmmmw2RsysHnjkS3vuijKpk9NJ8/yrBlY6RQI/8THveljnOB8AOsY17SnogTaUiyPmKpguw2WixCpaO9HXgTznYHL89A0EBz1cJc3eOS9egOYsHfm02fBoZU7a/3Deo/J4L9x6SOVNcx/DvSjMgsU086GzkCIl0Fo3Wx+wxHnWUUG6rReUHyadEf5Wbwa4MG12oFh+3XUUxr5sHQe1WY07WCrujvy+LoCJFhuYVOqh725p29ZeGiuOVZtif7yyY3jcYMHJ4TiSGrurjvkrN/HE63SzDLOkC8HdvwpON7hHABx+EpL+yMiG+EqlnqRqi5hZDnbqRhJhnTkICBprqnHNAlYAxucuROuWNl9473KwrQKXIj1VeXb9tDgxlJcIp4Rcp1pS54TMz/hLjtvc7Vj9p7dlKUvKLx+WZdtR+MD0bC7ja+im4zxQ31j+NbJJ3RMLMB1u0eEx6Sf5aU7WjzbzgV8mwn3VP4SDVUan62KVa/Wt/2MDMgV8=
    # FIREBASE_SECRET
    - secure: XyV8DAhJ9P7MWyjzmZqS7DTGJGSzgFFZ8yPYavcHQxmeAU5iIDB4aRHcN4SAfwnpbNfokeV4crZhkq40hgn7GrfgJ7k4pnKNgxNZAo/RF7s2s7JXhko0HZkgg2C1vWXSM9nGOSS5ItU5M1Poj8hIwk8bEWyUwDJoVdm+kBHKu4R4vpQGKXbcZNaQJf41P9zzliNMmrjBpTk8yagd/+aQp+SOJmOdY+kH6D+mdzp4UH9e0WYUsBmQKM4yTUpnoWWEDb+sJDeZPglDuZfCXQMyutsIpi+BJLsdrV1cXXd773nBApVkH3n6I60d94XQNlPGee8oNLqxYpKNiQmkU8g1kkSickz5RfEMzFkNskzgZLmdydWsUsRps8b/XdJg7NPAabFq7EXNKOsLuonQcHLBDae+TlcYH8JjfptDSaRa/UkIGeM4JqsOl+XiyTlevR6c4iXzuko7tRjaQCKw6+q0en86m7SiDxz0XaXubpabcZ8QAsvVBNQtdH0fRYS49dZIWp0uU/XwVE5vEoKLlmcs8iC1w9+djcMBej4kZMcbdT2IhJp2OeIVnIlKWh51Pv0QAZewgBn/qN7X7l5pmBv/BGizFPvpXeFKwoaTCe/9XRBO6RDonpstDWOn8JENiAr805mKArJCusA+RyhsOW7CPOhDHye8qcmUZNCFZADXARI=
